config: !!python/object:utils.experiment_configs.Configs
  config_dict:
    data: &id001
      dim: &id002
        context_continuous: 0
        context_discrete: 0
        features_continuous: 3
        features_discrete: 1
      source: &id003
        name: GaussNoise
        params: &id004
          max_num_particles: 128
          min_num_particles: 0
          scale: 1.0
        path: null
        preprocess: &id005
          continuous: null
          discrete: tokens
      target: &id006
        name: AspenOpenJets
        params: &id007
          max_num_particles: 128
          min_num_particles: 0
          num_jets: 1000
        path: &id008
        - /home/df630/CMB/data/AOJ/2016H_job0.h5
        preprocess: &id009
          continuous: standardize
          discrete: tokens
      vocab_size: &id010
        context: 0
        features: 8
    dynamics: &id011
      bridge_continuous: LinearUniformBridge
      bridge_discrete: TelegraphBridge
      params: &id012
        gamma: 0.125
        sigma: 0.0001
    experiment: &id013
      experiment_dir: null
      experiment_indentifier: null
      experiment_name: multimodal_brige_matching
    model: &id014
      activation: SELU
      add_discrete_head: true
      dim: &id015
        emb_context_continuous: 0
        emb_context_discrete: 0
        emb_features_continuous: 16
        emb_features_discrete: 16
        emb_time: 16
        hidden_glob: 16
        hidden_local: 16
      dropout: 0.1
      embedding: &id016
        context_continuous: null
        context_discrete: null
        features_continuous: Linear
        features_discrete: Embedding
        time: SinusoidalPositionalEncoding
      name: MultiModalEPiC
      num_blocks: 2
      skip_connection: true
    pipeline: &id017
      method: EulerLeapingSolver
      num_timesteps: 1000
      time_eps: 0.0001
    train: &id018
      batch_size: 1024
      data_split_frac: &id019
      - 0.8
      - 0.2
      - 0.0
      epochs: 200
      gradient_clip_val: 1.0
      optimizer: &id020
        name: AdamW
        params: &id022
          amsgrad: false
          betas: &id021
          - 0.9
          - 0.999
          eps: 1.0e-08
          lr: 0.001
          weight_decay: 5.0e-05
      scheduler: &id023
        name: CosineAnnealingLR
        params: &id024
          T_max: 1000
          eta_min: 5.0e-05
          last_epoch: -1
  data: !!python/object:utils.experiment_configs.Configs
    config_dict: *id001
    dim: !!python/object:utils.experiment_configs.Configs
      config_dict: *id002
      context_continuous: 0
      context_discrete: 0
      features_continuous: 3
      features_discrete: 1
    source: !!python/object:utils.experiment_configs.Configs
      config_dict: *id003
      name: GaussNoise
      params: !!python/object:utils.experiment_configs.Configs
        config_dict: *id004
        max_num_particles: 128
        min_num_particles: 0
        scale: 1.0
      path: null
      preprocess: !!python/object:utils.experiment_configs.Configs
        config_dict: *id005
        continuous: null
        discrete: tokens
        stats: null
    target: !!python/object:utils.experiment_configs.Configs
      config_dict: *id006
      name: AspenOpenJets
      params: !!python/object:utils.experiment_configs.Configs
        config_dict: *id007
        max_num_particles: 128
        min_num_particles: 0
        num_jets: 1000
      path: *id008
      preprocess: !!python/object:utils.experiment_configs.Configs
        config_dict: *id009
        continuous: standardize
        discrete: tokens
        stats:
          max:
          - 536.5
          - 0.9034209847450256
          - 0.8936483860015869
          mean:
          - 7.430624961853027
          - 0.0009611865971237421
          - -0.0015880638966336846
          min:
          - 0.0
          - -1.0412812232971191
          - -0.8988540172576904
          std:
          - 19.07619857788086
          - 0.254862904548645
          - 0.263653039932251
    vocab_size: !!python/object:utils.experiment_configs.Configs
      config_dict: *id010
      context: 0
      features: 8
  dynamics: !!python/object:utils.experiment_configs.Configs
    bridge_continuous: LinearUniformBridge
    bridge_discrete: TelegraphBridge
    config_dict: *id011
    params: !!python/object:utils.experiment_configs.Configs
      config_dict: *id012
      gamma: 0.125
      sigma: 0.0001
  experiment: !!python/object:utils.experiment_configs.Configs
    config_dict: *id013
    experiment_dir: null
    experiment_indentifier: null
    experiment_name: multimodal_brige_matching
    name: GaussNoise_to_AspenOpenJets_MultiModalEPiC_2025.01.03_02h17_2316
    type: multimodal
  model: !!python/object:utils.experiment_configs.Configs
    activation: SELU
    add_discrete_head: true
    config_dict: *id014
    dim: !!python/object:utils.experiment_configs.Configs
      config_dict: *id015
      emb_context_continuous: 0
      emb_context_discrete: 0
      emb_features_continuous: 16
      emb_features_discrete: 16
      emb_time: 16
      hidden_glob: 16
      hidden_local: 16
    dropout: 0.1
    embedding: !!python/object:utils.experiment_configs.Configs
      config_dict: *id016
      context_continuous: null
      context_discrete: null
      features_continuous: Linear
      features_discrete: Embedding
      time: SinusoidalPositionalEncoding
    name: MultiModalEPiC
    num_blocks: 2
    skip_connection: true
  pipeline: !!python/object:utils.experiment_configs.Configs
    config_dict: *id017
    method: EulerLeapingSolver
    num_timesteps: 1000
    time_eps: 0.0001
  train: !!python/object:utils.experiment_configs.Configs
    batch_size: 1024
    config_dict: *id018
    data_split_frac: *id019
    epochs: 200
    gradient_clip_val: 1.0
    optimizer: !!python/object:utils.experiment_configs.Configs
      config_dict: *id020
      name: AdamW
      params: !!python/object:utils.experiment_configs.Configs
        amsgrad: false
        betas: *id021
        config_dict: *id022
        eps: 1.0e-08
        lr: 0.001
        weight_decay: 5.0e-05
    scheduler: !!python/object:utils.experiment_configs.Configs
      config_dict: *id023
      name: CosineAnnealingLR
      params: !!python/object:utils.experiment_configs.Configs
        T_max: 1000
        config_dict: *id024
        eta_min: 5.0e-05
        last_epoch: -1
